modLoader="javafml"
loaderVersion="[43,)"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId="su_gems"
version="0.9.0"
displayName="SU Gems"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Ypno D."
description="A mod that adds things from the show Steven Universe!"

[[dependencies.su_gems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




